### ISSUE TITLE
TypeError: ranksums() got an unexpected keyword argument 'alternative'

### ISSUE THREAD

**Issue by HDEzhsw** [zhengrongbin/MEBOCOST#10]
When I was running the following code: 
commu_res = mebo_obj.infer_commu(
                                n_shuffle=1000,
                                seed=220808597, 
                                Return=True, 
                                thread=None,
                                save_permuation=False,
                                min_cell_number = 1
                            )
I keep encountering the error "TypeError: ranksums() got an unexpected keyword argument 'alternative'".

**Comment by zhengrongbin** [comment]
Hi - I guess this error came from the version problem of scipy. It should be upgraded to >= 1.3.0 according to the discussion here https://stackoverflow.com/questions/59148514/scipy-wilcoxon-throwing-typeerror-when-trying-to-specify-an-alternative-hypothes
