### ISSUE TITLE
The color that indicates the -log10(FDR) 

### ISSUE THREAD

**Issue by M1chelGom3s** [zhengrongbin/MEBOCOST#13]
Dear Dr. Zheng,
Thank you for providing MEBOCOST it is very useful to me.
I have a problem at the step showing the detailed communications with the mebo_obj.commu_dotmap.
The color that indicated the -log10(FDR) is either at max or at minimum.
My question is why I am not in between?
Thank you in advance.

<img src="https://user-images.githubusercontent.com/115038207/212642397-7e4afed0-a00d-44fa-bcd6-b0d640ed3402.png" width="150" height="280">

**Comment by zhengrongbin** [comment]
Hi - thank you for using MEBOCOST! This means that your FDR values may be very close. You can print the mebo_obj.commu_res to check the actual communication score and FDR values. Also, we use a permutation test to calculate the p-values then convert them to FDR, the more times of permutation (default 1000 times) may give you a more precise p-value calculation, but longer computing takes.

**Comment by M1chelGom3s** [comment]
Thank you for your response and suggestion. I will definitely check the mebo_obj.commu_res and consider increasing the number of permutations to get a more accurate p-value calculation. I appreciate your help with MEBOCOST.
