### ISSUE TITLE
I am curious about the communication score and have a question.

### ISSUE THREAD

**Issue by mybioinformatics** [zhengrongbin/MEBOCOST#15]
Hi, thanks for developing such a great tool. 

I am using your tool to analyze two conditions (ex Case vs Control).

The ultimate goal I am trying to find using your tool is a metabolite interaction that is upregulated or downregulated in Case vs Control (like DEG). 

So I did a comparative analysis the way you answered a question someone posted before and I have a question for you here. 

** (The comparative analysis method I referenced): https://github.com/zhengrongbin/MEBOCOST/issues/3

Q. If the interaction score for a particular metabolite pair is 3.4 (Comm_score) in Bcell~case to Bcell~case and -1.2 (Comm_score) in Bcell~control to Bcell~control, can we interpret that the autocrine interaction is upregulated in Bcell~case relative to Control ? 

Thanks.

**Comment by zhengrongbin** [comment]
Hi, Yes, I think you can understand in that way, as long as your data was processed and normalized together, and communication score was significant at least in one of the conditions.Best Regards!Rongbin ZhengOn Apr 27, 2023, at 2:34 AM, mybioinformatics ***@***.***> wrote:﻿
Hi, thanks for developing such a great tool.
I am using your tool to analyze two conditions (ex Case vs Control).
The ultimate goal I am trying to find using your tool is a metabolite interaction that is upregulated or downregulated in Case vs Control (like DEG).
So I did a comparative analysis the way you answered a question someone posted before and I have a question for you here.
** (The comparative analysis method I referenced): #3
Q. If the interaction score for a particular metabolite pair is 3.4 (Comm_score) in Bcellcase to Bcellcase and -1.2 (Comm_score) in Bcellcontrol to Bcellcontrol, can we interpret that the autocrine interaction is upregulated in Bcell~case relative to Control ?
Thanks.

**Comment by mybioinformatics** [comment]
Thanks for the quick reply :) 

If you can develop a function to do differential tests in the future, I think people will be more interested and use it more. 

I hope your tool gets published in a good journal !!!

**Comment by zhengrongbin** [comment]
> 

Thank you for the comment! We understand the importance of performing a comparison analysis between conditions, and we are definitely on the way to upgrading.
