### ISSUE TITLE
how to manually add new metabolites-sensor pair

### ISSUE THREAD

**Issue by KarryGoCarry** [zhengrongbin/MEBOCOST#17]
Hi, Thanks for developing this great tool.
I am wondering can I manually add new metabolites-sensor pair in mouse_met_sen_October-25-2022_14-52-47.tsv file?
I tried to add a new one myself, but the result do not contain the result I want.
(I already removed the expression filter before run mebocost, and the metabolite related enzyme is in metabolite_associated_gene_reaction_HMDB_summary_mouse.tsv)

**Comment by zhengrongbin** [comment]
Hi - Can you please first check your metabolite-sensor pair mebo_obj.original_result to make sure that new pair was filtered out due to low expression and other reasons? If the new pair was not even in the original result, that means the MEBCOOST didn’t recognize your editing in the table. In that case, we should discuss how to successfully add a new pair. Thanks!


Best,
Rongbin

**Comment by KarryGoCarry** [comment]
Thank you for the quick reply!!!
I think I already turned off all the filters by the below step you provided:

## initiate the mebocost object
mebo_obj = mebocost.create_obj(
                        adata = adata,
                        group_col = ['celltype'], # change to the group you want to split
                        met_est = 'mebocost',
                        config_path = './mebocost.conf',
                        exp_mat=None,
                        cell_ann=None,
                        species='mouse', # or human
                        met_pred=None,
                        met_enzyme=None,
                        met_sensor=None,
                        met_ann=None,
                        scFEA_ann=None,
                        compass_met_ann=None,
                        compass_rxn_ann=None,
                        gene_network=None,
                        gmt_path=None,
                        cutoff_exp=0, ## automated cutoff to exclude lowly ranked 25% sensors across all cells
                        cutoff_met=0, ## automated cutoff to exclude lowly ranked 25% metabolites across all cells
                        cutoff_prop=0, ## at lease 25% of cells should be expressed the sensor or present the metabolite in the cell group (specified by group_col)
                        sensor_type=['Receptor', 'Transporter', 'Nuclear Receptor'],
                        thread=8
                        )

## In order to add a new pair (Taurine -> Slc6a6), I manually input a new row in the "mouse_met_sen_October-25-2022_14-52-47.tsv", right after your last row.

445  HMDB0000251     Taurine   Taurine   Slc6a6     Sodium- and chloride-dependent taurine transporter    New       Transporter

I also checked the expression of the Taurine-related enzyme and Slc6a6 sensor expression in my data, and the looks just fine.

**Comment by zhengrongbin** [comment]
It is strange. That should work. Let me test and get back to you later. Thank you!

Best,
Rongbin

**Comment by zhengrongbin** [comment]
Hi - did you by any chance solve the problem? I tested and it works very well on my laptop. If you still have the problem, I would like to suggest checking the following things, to make sure that the edited metabolite-sensor table has been successfully updated in the MEBOCOST object. 
(1). check the mebo_obj.met_sensor to see if the Taurine-Slc6a6 in the table,
(2). check the mebo_obj.met_mat_index to see if the HMDB0000251 in the index ('HMDB0000251' in mebo_obj.met_mat_index.tolist())
(3). check the log file to see if MEBOCOST calculated the communication score for Taurine-Slc6a6. If so, you can find an entry containing Slc6a6 ~ HMDB0000251.

Please email me if you still have the problem after checking everything, we can probably have a ZOOM meeting to figure out the problem on your side together. Thanks!

**Comment by KarryGoCarry** [comment]
With Dr. Zheng's help, I solved my problem.
The error was caused by the expression data that Mebocost uses is the "scaled.data" in my scRNAseq which only contains 2000 top-varied genes. 
Since Mebocost requires h5ad file, so I when you create Mebocost input file from a pre-processed Seurat object remember to use the following code to remove "scaled.data" slot. The h5ad file will default use the slot "scaled.data", to get the full analysis you should use the full genes table instead: 



```
Seurat.obj = DietSeurat(object = Seurat.obj, counts = T, data = T, scale.data = F, assays = "RNA", dimreducs =c('pca','tsne','umap','harmony'))

SaveH5Seurat(Seurat.obj, filename = "Data/seurat.h5Seurat")
Convert("Data/seurat.h5Seurat", dest = "h5ad")
 
```
