### ISSUE TITLE
error in "Inference of pathway to the communications"

### ISSUE THREAD

**Issue by LipingChen0607** [zhengrongbin/MEBOCOST#2]
Dear Dr Zheng,
Thanks a lot for sharing your amazing work about MEBOCOST! However, when I run the module "Inference of pathway to the communications", there are some error like this in attachment. Could you give me some advice to deal with this problem? Thank you!

<img width="698" alt="截屏2022-06-03 下午8 17 44" src="https://user-images.githubusercontent.com/74603389/171852350-b019e144-7af5-4438-a3ca-ab687ee6a725.png">
<img width="701" alt="截屏2022-06-03 下午8 17 52" src="https://user-images.githubusercontent.com/74603389/171852367-91e0e30a-8e26-4ef2-ad07-ef26b53a387b.png">
<img width="686" alt="1" src="https://user-images.githubusercontent.com/74603389/171852382-5ae5b693-3ae5-4fe7-a37c-ddcc1fff82ed.png">
<img width="700" alt="2" src="https://user-images.githubusercontent.com/74603389/171852392-bcdf1d1b-ba11-45b1-a990-f6fc7715fec0.png">
<img width="689" alt="3" src="https://user-images.githubusercontent.com/74603389/171852398-1c29148b-1224-42df-93bf-f2fa82075286.png">
<img width="692" alt="4" src="https://user-images.githubusercontent.com/74603389/171852658-734087a5-8189-46a8-a5b6-2b32e1f516e2.png">

**Comment by zhengrongbin** [comment]
Hi Liping,

Thank you for reaching out. The error probably from the xlmhg package which we used as our statistical testing for pathway analysis. However, “ mhg_cython” is a codependency with xlmhg package, and it is seems currently supported at python 3.8 but not 3.9. Could you try to downgrade your python and re-install MEBOCOST. At least in my testing, the error disappeared at python 3.8. We use xlmhg package only in pathway analysis and don’t influence communication prediction, so the object you saved from communication prediction can still be loaded after MEBOCOST re-installed. Please let me if it works or not. Thanks!

Best,
Rongbin

**Comment by LipingChen0607** [comment]
Thanks a lot! When I downgrade python to 3.8, the program can run correctly.  It seems that pathway analysis can only run based on python3.8 now~
