### ISSUE TITLE
Can enzyme genes contributing to the inferred metabolite be extracted?

### ISSUE THREAD

**Issue by YaoyJiang** [zhengrongbin/MEBOCOST#22]
Hi Rongbin,

Thank you for providing such a useful tool. I've tested Mebocost on my personal scRNA-seq dataset, and it worked beautifully. I’m wondering whether the enzyme genes that contribute to the inferred metabolite could be extracted?

Thanks,
Yao Jiang

**Comment by zhengrongbin** [comment]
Yes, the metabolite and enzyme relationships can be found at mebo_obj.met_enzyme. We right now don't have specific function to extract the enzymes based on metabolite names, but everything is in the met_enzyme data frame. Best Regards!Rongbin ZhengOn May 18, 2024, at 3:39 PM, YaoyJiang ***@***.***> wrote:﻿
Hi Rongbin,
Thank you for providing such a useful tool. I've tested Mebocost on my personal scRNA-seq dataset, and it worked beautifully. I’m wondering whether the enzyme genes that contribute to the inferred metabolite could be extracted?
Thanks,
Yao Jiang
