### ISSUE TITLE
No communication events under pval_cutoff:0.05 and comm_score_cutoff:0, try to tune them!

### ISSUE THREAD

**Issue by AcetylCoALab** [zhengrongbin/MEBOCOST#23]
After I run mebo_obj.commu_network_plot it says
[June 17, 2024 22:24:37]: show communication in cells by network plot
[June 17, 2024 22:24:37]: No communication events under pval_cutoff:0.05 and comm_score_cutoff:0, try to tune them! 
Please tell me how I should adjust him.

**Comment by zhengrongbin** [comment]
Hi, this warning tells that the plotting function gets zero event to plot. Basically you don't have any significant communication identified by the default intuitive cutoffs. It is hard to figure out what happened simply by this warning. Can you please provide more log information, such as those from create object and infer communication. Thanks!Best Regards!Rongbin ZhengOn Jun 17, 2024, at 10:26 AM, Jingyuan Ning ***@***.***> wrote:﻿
当我运行mebo_obj.commu_network_plot以后提示
[June 17, 2024 22:24:37]: show communication in cells by network plot
[June 17, 2024 22:24:37]: No communication events under pval_cutoff:0.05 and comm_score_cutoff:0, try to tune them!
请问我应该怎样调整他。

**Comment by seekning** [comment]
> After I run mebo_obj.commu_network_plot it says运行 mebo_obj.commu_network_plot 后，它说 [June 17, 2024 22:24:37]: show communication in cells by network plot[2024 年 6 月 17 日 22：24：37]：按网络图显示单元格中的通信 [June 17, 2024 22:24:37]: No communication events under pval_cutoff:0.05 and comm_score_cutoff:0, try to tune them![2024 年 6 月 17 日 22：24：37]：pval_cutoff：0.05 和 comm_score_cutoff：0 以下没有通信事件，请尝试调整它们！ Please tell me how I should adjust him.请告诉我我应该如何调整他。



> After I run mebo_obj.commu_network_plot it says运行 mebo_obj.commu_network_plot 后，它说 [June 17, 2024 22:24:37]: show communication in cells by network plot[2024 年 6 月 17 日 22：24：37]：按网络图显示单元格中的通信 [June 17, 2024 22:24:37]: No communication events under pval_cutoff:0.05 and comm_score_cutoff:0, try to tune them![2024 年 6 月 17 日 22：24：37]：pval_cutoff：0.05 和 comm_score_cutoff：0 以下没有通信事件，请尝试调整它们！ Please tell me how I should adjust him.请告诉我我应该如何调整他。

hallo，跪拜dalao

**Comment by zhengrongbin** [comment]
Hi, have you figured out? I did not hear from you about more log information. There is a common mistake causing such a error - did you load expression for all 20k genes? Sometimes, people just loaded highly variable genes (~2k) so that mebocost didn't get rigth data to perform the analysis, that is one of the reasons you cannot see any communications.
