### ISSUE TITLE
 Is it feasible to measure the content of various metabolites in cells using MEBOCOST?

### ISSUE THREAD

**Issue by jouska540** [zhengrongbin/MEBOCOST#28]
Thank you for providing such a useful tool. I am very eager to use your method to measure metabolite levels through scRNA data. I would like to ask how many kinds of metabolite expression levels can be estimated through MEBOCOST? You mentioned that only metabolites whose upstream enzymes have gene annotations will have an estimate. My question is whether all metabolites that meet this criterion are applicable, or is it necessary for metabolites with downstream receptors. Because I noticed in your metabolite_associated_gene_reaction_HMDB_summary file that ceramide - a metabolite whose enzyme has gene annotations is indeed not included in metabolic substrates or products. So, it seems that ceramide level can't be estimated through MEBOCOST

Additionally, I would like to consult you. Is there any other way besides mebocost to estimate metabolite levels as much as possible through single-cell data?

**Comment by zhengrongbin** [comment]
Hi, first of all, mebocost aggregate enzyme gene expression in the analysis. The aggregation considers both producing enzymes and consuming enzymes in the calculation (please refer to our bioRxiv paper for the exact calculation). Based on our observation, the aggregate values can be correlated with metabolite level but the correlation coefficients vary a lot across metabolites, instead, the aggregated values more reflect the metabolite existence, that is why we call it metabolite presence. For your questions, here is my anwsers:

**how many kinds of metabolite expression levels can be estimated through MEBOCOST?**
Answer: it depends. all the metabolites with enzyme genes will be calculated but will depends on if the enzyme genes were detected in your scRNA-seq data.

 **it seems that ceramide level can't be estimated through MEBOCOST**
Answer: you are right. The mebocost will not have it if no enzyme provided for that metabolite. If the enzymes are known and missed in our collection, please kindly let me know, I can add in our next update. You can also modify the reaction file to add them by yourself. 

**My question is whether all metabolites that meet this criterion are applicable, or is it necessary for metabolites with downstream receptors.**
Answer: I am not sure if I get you correctly. I believe it is still applicable for metabolites with downstream receptors, as the aggregated enzyme values of metabolites will be used to characterize sender cells, while receptors only used for receiver cells. Please correct me if I misunderstood you.
