### ISSUE TITLE
Can’t open the tutorial file

### ISSUE THREAD

**Issue by wuxiangning** [zhengrongbin/MEBOCOST#29]
Hello！
Why can’t I open the tutorial file directly from the README anymore? It shows a 404 error. Is there an issue? 
Thanks!
![{433FDB14-2FC2-485B-8EFA-B7A74B5211C2}](https://github.com/user-attachments/assets/435ec2ee-2edc-4efe-b293-bf76f2bcd8d4)

**Comment by zhengrongbin** [comment]
Hi, it was because the package has been moved to the lab's github page, and only supports for v1.0.4. I have hyperlink in the readme page, it should work now and can direct you to the new tutorial.
