### ISSUE TITLE
Is it feasible to measure the content of various metabolites in bulk RNAseq using MEBOCOST?

### ISSUE THREAD

**Issue by shineshen007** [zhengrongbin/MEBOCOST#30]

**Comment by zhengrongbin** [comment]
Hi, it is not recommended to use mebocost to predict "metabolite abundance" (if I understand your question correctly), mebocost aggregates metabolite producing enzymes and consuming enzymes in the network to represent the activity of the biosynthesis pathway. If you were applying it to bulk RNA-seq, I would interpret the result as an averaged activity of metabolite biosynthesis pathway.

**Comment by shineshen007** [comment]
Thanks
