### ISSUE TITLE
save the image

### ISSUE THREAD

**Issue by 1378989** [zhengrongbin/MEBOCOST#5]
![image](https://user-images.githubusercontent.com/85168692/177005540-b7c32ca0-499b-49a6-bf5f-87b71a635ecc.png)
![image](https://user-images.githubusercontent.com/85168692/177005546-c891cbff-a0dc-40be-85f2-21039c4a8085.png)

Dear Mr zheng,why save the image have error?
Thank you for helping me solve the error!!

**Comment by zhengrongbin** [comment]
Hi - please provide a file name to "save" to avoid this error!
