### ISSUE TITLE
Config path error

### ISSUE THREAD

**Issue by jackbrougher** [zhengrongbin/MEBOCOST#7]
Hello,

Thanks for developing the great tool!

I'm running through your first tutorial but with a pre-existing annotated dataset of my own. I'm hitting an error at step 2.2 when running the code you've supplied. Specifically, the error is: KeyError: 'ERROR: the config path is not exist!'

Do I need to re-install? Any tips?

**Comment by jackbrougher** [comment]
I'm a dummy, please disregard!

**Comment by ngmyy** [comment]
Have you solved the problem? I had the same problem.

**Comment by zhengrongbin** [comment]
> Have you solved the problem? I had the same problem.

Hi, the config path should be a relative or an absolute path to tell the location of mebocost.conf file in your laptop or other working space. You will not get the error if you run the notebook under the MEBOCOST folder downloaded from GitHub. If you run a notebook from a different folder, you must modify "config_path = './mebocost.conf'," and replace the './mebocost.conf' with the right path of mebocost.conf file. 

I would recommend running the notebook under the MEBOCOST folder that you downloaded from GitHub if you cannot figure out the folder structure.

**Comment by CGAfresh** [comment]
my solution is this:
current_directory = os.getcwd()
print('当前工作目录是:', current_directory)
os.chdir('/home/newuser/MEBOCOST')
# 获取当前工作目录
current_directory = os.getcwd()
print('当前工作目录是:', current_directory)
from mebocost import mebocost
