### ISSUE TITLE
DEMO dataset also showed some errors

### ISSUE THREAD

**Issue by jiangzh-coder** [zhengrongbin/MEBOCOST#9]
WHAT i run is DEMO dataset.
![image](https://user-images.githubusercontent.com/68450512/200274677-eeda8dd0-3891-4a60-a6ae-e1c0f887b68b.png)
![image](https://user-images.githubusercontent.com/68450512/200274736-be7b6c45-cebc-485a-88cb-0767958b5868.png)

**Comment by jiangzh-coder** [comment]
![image](https://user-images.githubusercontent.com/68450512/200274884-ee19fbc9-5924-4632-8465-36986fdf8de3.png)

**Comment by zhengrongbin** [comment]
Thanks for the question! Please make sure your config path is given correctly. The config file should be provided by 
```
config_path = './mebocost.conf'
```
where ./mebocost.conf is the relative path. If you change your workspace to other folders rather than the MEBOCOST folder, you need to revise the config_path, or you can provide an absolute file path. Please let me if you still get questions!

**Comment by jiangzh-coder** [comment]
for the 1st figure, i can not read anything. could you help me?
![image](https://user-images.githubusercontent.com/68450512/200338114-19ff08b8-877d-4886-8270-37abb09db13e.png)

**Comment by jiangzh-coder** [comment]
![Figure_1](https://user-images.githubusercontent.com/68450512/200338256-60c92160-02ff-4688-be22-60989d13880f.png)

**Comment by jiangzh-coder** [comment]
also, no communication error

![image](https://user-images.githubusercontent.com/68450512/200339593-dad6f06a-0cfa-45eb-a94d-03d14fee18fa.png)

**Comment by zhengrongbin** [comment]
Looks like this is your own data, not demo data. I think the error comes from empty communications. We will fix this error by printing out a warning msg later. Together with your case reported in #8, I am happy to set up a meeting with you, so we can have better communications to solve the problem efficiently.  Please feel free to send me an email to set up a ZOOM meeting when you are ready. My email address: Rongbin.Zheng@childrens.harvard.edu
